steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.streamlit', '-t',
           'us-central1-docker.pkg.dev/amazon-launch/amazon-predictor/app:streamlit', '.']
images:
  - 'us-central1-docker.pkg.dev/amazon-launch/amazon-predictor/app:streamlit'
